### ISSUE TITLE
Unclear what collection.Remove does

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sn-client-js#1]
If I call **Remove** on a SenseNet _Collection_, does it delete the content **from the server** or it only removes the content locally from the collection?

**Comment by tusmester** [comment]
Not sure if this should be addressed by documentation or should we rename the method to **Delete**? Because what if I wanted to work with a collection locally, without managing content on the server? Should I use this collection for that or only a simple js array?

**Comment by herflis** [comment]
Remove on collection means now that you remove a content from the collection locally AND from the server at the same time. It's almost the same as call Content.Delete on a selected item in the collection. So I think Remove is a better name, because you may think that with Collection.Delete you will delete the whole collection. 
What if the content and collection related methods (if it that make sense) had an optional param where you can define that you want to execute them only locally or on the server too?

**Comment by tusmester** [comment]
You'll also have to "route" other parameters of these methods - in case of Delete/Remove this means the "permanent" option that bypasses the Trash. I agree with you on the name, and there are not too many methods of this kind anyway :)

**Comment by herflis** [comment]
FYI other params like permanently and many others can be added OPTIONALLY. Check the docs: http://download.sensenet.com/aniko/sn7/jsapidocs/classes/_collection_.collection.html#remove ;)

**Comment by tusmester** [comment]
So....RTFM :)
